In [32]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import math

In [41]:
df = pd.read_csv("homeprices.csv")
df



area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [42]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [43]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)

In [44]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [45]:
model =linear_model.LinearRegression()
model.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [46]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [47]:
model.intercept_

221323.00186540408

In [48]:
model.predict([[3000,3,40]])

array([498408.25158031])

In [49]:
(112.06244194*3000+23388.88007794*3+-3231.71790863*40)+221323.00186540408

498408.2515740241

In [50]:
import pickle

In [53]:
with open('model_pickle','wb')as f:
    pickle.dump(model,f)

In [56]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

In [62]:
mp.predict([[3000,3,40]])

array([498408.25158031])

In [67]:
import joblib

In [65]:
!pip install joblib

In [68]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [69]:
mj= joblib.load('model_joblib')

In [70]:
mj.predict([[3000,3,40]])

array([498408.25158031])

In [71]:
mj.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [72]:
mj.intercept_

221323.00186540408